namespace peremenie
{
    internal class Program
    {
        static void Main(string[] args)
        {
            // Переменные

            byte gold;
            sbyte titan;
            short phone;
            ushort apple;
            int star;
            uint melon;
            long packet;
            ulong book;
        }
    }
}
